### ISSUE TITLE
SSL is invalid

### ISSUE THREAD

**Issue by tiborsaas** [thebakeryio/openmic#12]
Hey guys, 

Chrome throws a big halt screen because SSL certificate is off.

![image](https://cloud.githubusercontent.com/assets/342688/17176206/de24ad62-540b-11e6-889c-7ef45dff4f53.png)

**Comment by callmephilip** [comment]
this is new. gonna investigate 👓

**Comment by callmephilip** [comment]
@tiborsaas : should be good now

**Comment by tiborsaas** [comment]
What the boss said :) 
:boom:
